site_name: Non-Markovian Methods

theme:
  name: "material"


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_submodules: true
  - search
  - mkdocs-jupyter

nav:
- NonMarkovianMethods Documentation: index.md
- API reference: api.md
- Example 1: example_qutip.ipynb
- Example 2 : Qubit_example.ipynb
- Theory: theory.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js