site_name: Non-Markovian Methods
site_url: https://gsuarezr.github.io/NonMarkovianMethods/

theme:
  name: "material"


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_submodules: true
  - search
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"

nav:
- NonMarkovianMethods Documentation: index.md
- API reference: api.md
- Example 1: example_qutip.ipynb
- Example 2 : Qubit_example.ipynb
- Example 3: transport_example.ipynb
- Example 4: kerr_example.ipynb 
- Example 5: damped_jc.ipynb

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js