[build-system]
requires = ["setuptools>=61.0","cython",'numpy',
        'scipy; python_version > "3.7"',
        'jax',
        'jaxlib',
        'multipledispatch']
build-backend = "setuptools.build_meta"
