name: CI

on:
  push:
  pull_request:

jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        python-version:
        - "3.7.17"
        - "3.8.18"
        - "3.9.18"
        - "3.10.13"
        - "3.11.7"
        - "3.12.1"
    name: Test
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: $${{matrix.python-version}}
    - name: Install dependencies
      run: |
            python -m pip install pytest .
            python -m pip install -r requirements.txt
    - name: Run tests
      run: pytest

